### PR TITLE
Add links and a tad more instruction

### PR DESCRIPTION
**Pull request by wibeasley**
to help those unfamiliar with GitHub (as many REDCap admins seem to be)

### CODE REVIEW

**Comment by sburns** [comment]
> (as many REDCap admins seem to be)
> :disappointed:

**Comment by wibeasley** [comment]
@sburns, not to be pushy, but are you aware that I can't merge/pull into this repository?  I'm telling you in case you are waiting on me to accept these PRs.

image

**Comment by sburns** [comment]
I made you an Owner on the organization.

**Comment by wibeasley** [comment]
Thanks.  I'm happy either way, I just wanted to make sure you weren't waiting on me.

I'll still do PRs for any major changes, and wait for feedback.

**Pull request merged**
