### PR TITLE
Move projects and resources to data files, update template

### LINKED ISSUE #8: Fix table of projects
The table i just added is bad, 
- [x] it needs some CSS to make it legible
- [x] I need to figure out why the badges aren't linking correctly on github.io.

image

### PR DESCRIPTION
**Pull request by sburns**
Fixes #8 

By moving the projects and resource to data files we can:
1. Write actual HTML in the template (tables and markdown don't jive).
2. Make it easier for other devs to contribute their notes (no need to write html, just a few lines in the data files).

I used bootstrap's table classes to clean things up a bit.

### CODE REVIEW

**Comment by haozhu233** [comment]
Looks great!! :+1:

**Comment by sburns** [comment]
(Note those vendor:unresponsive shields should be fixed when the request is coming from github)

**Comment by wibeasley** [comment]
@sburns, that's slick.  I like the yaml encapsulation and the table formatting.  That's much easier to read and maintain.

**Pull request merged**
