### PR TITLE
Add redcapcustodian to the Applications section

### PR DESCRIPTION
**Pull request by pbchase**
I'm not sure if I put us in the right section. We have an R library and it is most of the code, but the study_template and its Dockerfile, build and deployment scripts, and cron examples are very valuable components.

### CODE REVIEW

**Comment by wibeasley** [comment]
@pbchase, 
1. how do you feel about removing that last sentence (eg, "See...")?  This link should already be supplied in the table's first column
2. I like that you are very thorough on the four programming languages, but it may look funny jammed in that skinny column.  After I merge the PR and see how it looks, I might move the details to the `description` field.

This should close https://github.com/ctsit/redcapcustodian/issues/84.

**Comment by pbchase** [comment]
The link in the description goes to the PKG down site while the first column links goes to the repo. Should I just embrace the PKG down link?

I understand your concern about the 4 languages. I rendered the site locally. I was on the fence about whether it was ok or not

**Comment by wibeasley** [comment]
> The link in the description goes to the PKG down site while the first column links goes to the repo. Should I just embrace the PKG down link?

Yep, you get one url.  Chose wisely.

But seriously, I think just the pkgdown url.  The repo is just one click away from the pkgdown site.  Removing the last sentence will keep the page more concise.  And the entries on the page will be more consistent.

**Comment by pbchase** [comment]
@wibeasley I implemented your less-is-more suggestions.

**Review by wibeasley — APPROVED** [review]

**Comment by wibeasley** [comment]
@pbchase, here's how it looks on the public site.  Are you happy with it?

It seems a shame that docker isn't mentioned.  I think that's a distinctive feature/distinguisher.

If you're happy --then cool.  If you want to include docker in the language or description column, I'll happily merge another PR.

image

**Comment by pbchase** [comment]
So you don't like Docker absence from the text either? Let's fix it then. Here are two options for the description text. 

> Simplifies data management activities on REDCap systems. It provides a Docker framework for automating data extraction, transformation, and loading (ETL) work with a focus on REDCap workflows and maintenance tasks.

or 

> Simplifies data management activities on REDCap systems. It provides a framework for automating data extraction, transformation, and loading (ETL) work with a focus on REDCap workflows and maintenance tasks. Uses Docker, shell script, and cron to automate workflows.

**Comment by wibeasley** [comment]
I like it.  Thanks, @pbchase.

image

**Pull request merged**
